services:
  cache:
    image: "redis:alpine"
    container_name: goship_cache
    ports:
      - "127.0.0.1:${HOST_CACHE_PORT-6379}:6379"

  mailpit:
    image: axllent/mailpit
    container_name: goship_mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "${HOST_MAILPIT_HTTP_PORT-8025}:8025"
      - "${HOST_MAILPIT_SMTP_PORT-1025}:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
